# Alex's Mobs - Give All Custom Items
give @s alexsmobs:acacia_blossom 1
give @s alexsmobs:ambergris 1
give @s alexsmobs:ancient_dart 1
give @s alexsmobs:banana 1
give @s alexsmobs:banana_peel 1
give @s alexsmobs:banana_slug_slime 1
give @s alexsmobs:banana_slug_slime_block 1
give @s alexsmobs:banana_slug_slime_block_bubbles 1
give @s alexsmobs:banana_slug_slime_block_inventory 1
give @s alexsmobs:banner_pattern_australia_0 1
give @s alexsmobs:banner_pattern_australia_1 1
give @s alexsmobs:banner_pattern_bear 1
give @s alexsmobs:banner_pattern_brazil 1
give @s alexsmobs:banner_pattern_new_mexico 1
give @s alexsmobs:bear_dust 1
give @s alexsmobs:bear_fur 1
give @s alexsmobs:bird_feeder 1
give @s alexsmobs:bird_feeder_hanging 1
give @s alexsmobs:bison_carpet 1
give @s alexsmobs:bison_fur 1
give @s alexsmobs:bison_fur_block 1
give @s alexsmobs:blobfish 1
give @s alexsmobs:blobfish_bucket 1
give @s alexsmobs:blood_gun_empty 1
give @s alexsmobs:blood_sac 1
give @s alexsmobs:blood_sprayer 1
give @s alexsmobs:blood_sprayer_empty 1
give @s alexsmobs:boiled_emu_egg 1
give @s alexsmobs:bone_serpent_tooth 1
give @s alexsmobs:cachalot_whale_tooth 1
give @s alexsmobs:caiman_egg 1
give @s alexsmobs:capsid 1
give @s alexsmobs:centipede_leg 1
give @s alexsmobs:centipede_leggings 1
give @s alexsmobs:chorus_on_a_stick 1
give @s alexsmobs:cockroach_ootheca 1
give @s alexsmobs:cockroach_wing 1
give @s alexsmobs:cockroach_wing_fragment 1
give @s alexsmobs:comb_jelly_bucket 1
give @s alexsmobs:cooked_catfish 1
give @s alexsmobs:cooked_kangaroo_meat 1
give @s alexsmobs:cooked_lobster_tail 1
give @s alexsmobs:cooked_moose_ribs 1
give @s alexsmobs:cosmic_cod 1
give @s alexsmobs:cosmic_cod_bucket 1
give @s alexsmobs:crocodile_chestplate 1
give @s alexsmobs:crocodile_egg 1
give @s alexsmobs:crocodile_scute 1
give @s alexsmobs:crystalized_banana_slug_mucus 1
give @s alexsmobs:devils_hole_pupfish_bucket 1
give @s alexsmobs:dimensional_carver 1
give @s alexsmobs:dimensional_carver_shard_0 1
give @s alexsmobs:dimensional_carver_shard_1 1
give @s alexsmobs:dimensional_carver_shard_10 1
give @s alexsmobs:dimensional_carver_shard_2 1
give @s alexsmobs:dimensional_carver_shard_3 1
give @s alexsmobs:dimensional_carver_shard_4 1
give @s alexsmobs:dimensional_carver_shard_5 1
give @s alexsmobs:dimensional_carver_shard_6 1
give @s alexsmobs:dimensional_carver_shard_7 1
give @s alexsmobs:dimensional_carver_shard_8 1
give @s alexsmobs:dimensional_carver_shard_9 1
give @s alexsmobs:dropbear_claw 1
give @s alexsmobs:echolocator 1
give @s alexsmobs:elastic_tendon 1
give @s alexsmobs:emu_egg 1
give @s alexsmobs:emu_feather 1
give @s alexsmobs:emu_leggings 1
give @s alexsmobs:enderiophage_rocket 1
give @s alexsmobs:ender_residue 1
give @s alexsmobs:endolocator 1
give @s alexsmobs:end_pirate_anchor 1
give @s alexsmobs:end_pirate_anchor_winch 1
give @s alexsmobs:end_pirate_door 1
give @s alexsmobs:end_pirate_flag 1
give @s alexsmobs:end_pirate_ship_wheel 1
give @s alexsmobs:end_pirate_trapdoor 1
give @s alexsmobs:end_pirate_trapdoor_bottom 1
give @s alexsmobs:end_pirate_trapdoor_open 1
give @s alexsmobs:end_pirate_trapdoor_top 1
give @s alexsmobs:falconry_glove 1
give @s alexsmobs:falconry_glove_hand 1
give @s alexsmobs:falconry_glove_inventory 1
give @s alexsmobs:falconry_hood 1
give @s alexsmobs:farseer_arm 1
give @s alexsmobs:fedora 1
give @s alexsmobs:fish_bones 1
give @s alexsmobs:fish_oil 1
give @s alexsmobs:flying_fish 1
give @s alexsmobs:flying_fish_boots 1
give @s alexsmobs:flying_fish_bucket 1
give @s alexsmobs:frilled_shark_bucket 1
give @s alexsmobs:frontier_cap 1
give @s alexsmobs:froststalker_helmet 1
give @s alexsmobs:froststalker_horn 1
give @s alexsmobs:gazelle_horn 1
give @s alexsmobs:ghostly_pickaxe 1
give @s alexsmobs:gongylidia 1
give @s alexsmobs:guster_eye 1
give @s alexsmobs:gustmaker 1
give @s alexsmobs:halo 1
give @s alexsmobs:hemolymph_blaster 1
give @s alexsmobs:hemolymph_blaster_empty 1
give @s alexsmobs:hemolymph_sac 1
give @s alexsmobs:hummingbird_feeder 1
give @s alexsmobs:kangaroo_burger 1
give @s alexsmobs:kangaroo_hide 1
give @s alexsmobs:kangaroo_meat 1
give @s alexsmobs:komodo_spit 1
give @s alexsmobs:komodo_spit_bottle 1
give @s alexsmobs:large_catfish_bucket 1
give @s alexsmobs:lava_bottle 1
give @s alexsmobs:leafcutter_anthill 1
give @s alexsmobs:leafcutter_ant_chamber 1
give @s alexsmobs:leafcutter_ant_pupa 1
give @s alexsmobs:lobster_bucket 1
give @s alexsmobs:lobster_tail 1
give @s alexsmobs:lost_tentacle 1
give @s alexsmobs:maggot 1
give @s alexsmobs:maraca 1
give @s alexsmobs:medium_catfish_bucket 1
give @s alexsmobs:mimicream 1
give @s alexsmobs:mimic_octopus_bucket 1
give @s alexsmobs:moose_antler 1
give @s alexsmobs:moose_headgear 1
give @s alexsmobs:moose_ribs 1
give @s alexsmobs:mosquito_larva 1
give @s alexsmobs:mosquito_proboscis 1
give @s alexsmobs:mosquito_repellent_stew 1
give @s alexsmobs:mudskipper_bucket 1
give @s alexsmobs:mungal_spores 1
give @s alexsmobs:music_disc_daze 1
give @s alexsmobs:music_disc_thime 1
give @s alexsmobs:mysterious_worm 1
give @s alexsmobs:novelty_hat 1
give @s alexsmobs:phantom_sail 1
give @s alexsmobs:pigshoes 1
give @s alexsmobs:platypus_bucket 1
give @s alexsmobs:platypus_egg 1
give @s alexsmobs:pocket_sand 1
give @s alexsmobs:poison_bottle 1
give @s alexsmobs:potted_flutter 1
give @s alexsmobs:pupfish_locator 1
give @s alexsmobs:pupfish_locator_in_chunk 1
give @s alexsmobs:purpur_planks 1
give @s alexsmobs:purpur_planks_slab 1
give @s alexsmobs:purpur_planks_stairs 1
give @s alexsmobs:purpur_planks_wall 1
give @s alexsmobs:raccoon_tail 1
give @s alexsmobs:rainbow_glass 1
give @s alexsmobs:rainbow_jelly 1
give @s alexsmobs:rattlesnake_rattle 1
give @s alexsmobs:raw_catfish 1
give @s alexsmobs:red_sand_circle 1
give @s alexsmobs:roadrunner_boots 1
give @s alexsmobs:roadrunner_feather 1
give @s alexsmobs:rocky_chestplate 1
give @s alexsmobs:rocky_shell 1
give @s alexsmobs:sail 1
give @s alexsmobs:sand_circle 1
give @s alexsmobs:sculk_boomer 1
give @s alexsmobs:serrated_shark_tooth 1
give @s alexsmobs:shark_tooth 1
give @s alexsmobs:shark_tooth_arrow 1
give @s alexsmobs:shattered_dimensional_carver 1
give @s alexsmobs:shed_snake_skin 1
give @s alexsmobs:shield_of_the_deep 1
give @s alexsmobs:shield_of_the_deep_blocking 1
give @s alexsmobs:shrimp_fried_rice 1
give @s alexsmobs:skelewag_sword 1
give @s alexsmobs:skelewag_sword_blocking 1
give @s alexsmobs:skelewag_sword_hand 1
give @s alexsmobs:skelewag_sword_inventory 1
give @s alexsmobs:skreecher_soul 1
give @s alexsmobs:skunk_spray 1
give @s alexsmobs:small_catfish_bucket 1
give @s alexsmobs:sombrero 1
give @s alexsmobs:sombrero_upside_down 1
give @s alexsmobs:sopa_de_macaco 1
give @s alexsmobs:soul_heart 1
give @s alexsmobs:spawn_egg_alligator_snapping_turtle 1
give @s alexsmobs:spawn_egg_anaconda 1
give @s alexsmobs:spawn_egg_anteater 1
give @s alexsmobs:spawn_egg_bald_eagle 1
give @s alexsmobs:spawn_egg_banana_slug 1
give @s alexsmobs:spawn_egg_bison 1
give @s alexsmobs:spawn_egg_blobfish 1
give @s alexsmobs:spawn_egg_blue_jay 1
give @s alexsmobs:spawn_egg_bone_serpent 1
give @s alexsmobs:spawn_egg_bunfungus 1
give @s alexsmobs:spawn_egg_cachalot_whale 1
give @s alexsmobs:spawn_egg_caiman 1
give @s alexsmobs:spawn_egg_capuchin_monkey 1
give @s alexsmobs:spawn_egg_catfish 1
give @s alexsmobs:spawn_egg_centipede 1
give @s alexsmobs:spawn_egg_cockroach 1
give @s alexsmobs:spawn_egg_comb_jelly 1
give @s alexsmobs:spawn_egg_cosmaw 1
give @s alexsmobs:spawn_egg_cosmic_cod 1
give @s alexsmobs:spawn_egg_crimson_mosquito 1
give @s alexsmobs:spawn_egg_crocodile 1
give @s alexsmobs:spawn_egg_crow 1
give @s alexsmobs:spawn_egg_devils_hole_pupfish 1
give @s alexsmobs:spawn_egg_dropbear 1
give @s alexsmobs:spawn_egg_elephant 1
give @s alexsmobs:spawn_egg_emu 1
give @s alexsmobs:spawn_egg_endergrade 1
give @s alexsmobs:spawn_egg_enderiophage 1
give @s alexsmobs:spawn_egg_farseer 1
give @s alexsmobs:spawn_egg_flutter 1
give @s alexsmobs:spawn_egg_fly 1
give @s alexsmobs:spawn_egg_flying_fish 1
give @s alexsmobs:spawn_egg_frilled_shark 1
give @s alexsmobs:spawn_egg_froststalker 1
give @s alexsmobs:spawn_egg_gazelle 1
give @s alexsmobs:spawn_egg_gelada_monkey 1
give @s alexsmobs:spawn_egg_giant_squid 1
give @s alexsmobs:spawn_egg_gorilla 1
give @s alexsmobs:spawn_egg_grizzly_bear 1
give @s alexsmobs:spawn_egg_guster 1
give @s alexsmobs:spawn_egg_hammerhead_shark 1
give @s alexsmobs:spawn_egg_hummingbird 1
give @s alexsmobs:spawn_egg_jerboa 1
give @s alexsmobs:spawn_egg_kangaroo 1
give @s alexsmobs:spawn_egg_komodo_dragon 1
give @s alexsmobs:spawn_egg_laviathan 1
give @s alexsmobs:spawn_egg_leafcutter_ant 1
give @s alexsmobs:spawn_egg_lobster 1
give @s alexsmobs:spawn_egg_maned_wolf 1
give @s alexsmobs:spawn_egg_mantis_shrimp 1
give @s alexsmobs:spawn_egg_mimicube 1
give @s alexsmobs:spawn_egg_mimic_octopus 1
give @s alexsmobs:spawn_egg_moose 1
give @s alexsmobs:spawn_egg_mudskipper 1
give @s alexsmobs:spawn_egg_mungus 1
give @s alexsmobs:spawn_egg_murmur 1
give @s alexsmobs:spawn_egg_orca 1
give @s alexsmobs:spawn_egg_platypus 1
give @s alexsmobs:spawn_egg_potoo 1
give @s alexsmobs:spawn_egg_raccoon 1
give @s alexsmobs:spawn_egg_rain_frog 1
give @s alexsmobs:spawn_egg_rattlesnake 1
give @s alexsmobs:spawn_egg_rhinoceros 1
give @s alexsmobs:spawn_egg_roadrunner 1
give @s alexsmobs:spawn_egg_rocky_roller 1
give @s alexsmobs:spawn_egg_seagull 1
give @s alexsmobs:spawn_egg_seal 1
give @s alexsmobs:spawn_egg_shoebill 1
give @s alexsmobs:spawn_egg_skelewag 1
give @s alexsmobs:spawn_egg_skreecher 1
give @s alexsmobs:spawn_egg_skunk 1
give @s alexsmobs:spawn_egg_snow_leopard 1
give @s alexsmobs:spawn_egg_soul_vulture 1
give @s alexsmobs:spawn_egg_spectre 1
give @s alexsmobs:spawn_egg_straddler 1
give @s alexsmobs:spawn_egg_stradpole 1
give @s alexsmobs:spawn_egg_sugar_glider 1
give @s alexsmobs:spawn_egg_sunbird 1
give @s alexsmobs:spawn_egg_tarantula_hawk 1
give @s alexsmobs:spawn_egg_tasmanian_devil 1
give @s alexsmobs:spawn_egg_terrapin 1
give @s alexsmobs:spawn_egg_tiger 1
give @s alexsmobs:spawn_egg_toucan 1
give @s alexsmobs:spawn_egg_triops 1
give @s alexsmobs:spawn_egg_tusklin 1
give @s alexsmobs:spawn_egg_underminer 1
give @s alexsmobs:spawn_egg_void_worm 1
give @s alexsmobs:spawn_egg_warped_mosco 1
give @s alexsmobs:spawn_egg_warped_toad 1
give @s alexsmobs:spectre_sail 1
give @s alexsmobs:spiked_scute 1
give @s alexsmobs:spiked_turtle_shell 1
give @s alexsmobs:squid_grapple 1
give @s alexsmobs:stink_bottle 1
give @s alexsmobs:stink_ray 1
give @s alexsmobs:stink_ray_empty_hand 1
give @s alexsmobs:stink_ray_empty_inventory 1
give @s alexsmobs:stink_ray_hand 1
give @s alexsmobs:stink_ray_hand_base 1
give @s alexsmobs:stink_ray_inventory 1
give @s alexsmobs:straddleboard 1
give @s alexsmobs:straddle_helmet 1
give @s alexsmobs:straddle_saddle 1
give @s alexsmobs:straddlite 1
give @s alexsmobs:straddlite_block 1
give @s alexsmobs:stradpole_bucket 1
give @s alexsmobs:tab_icon 1
give @s alexsmobs:tarantula_hawk_elytra 1
give @s alexsmobs:tarantula_hawk_elytra_broken 1
give @s alexsmobs:tarantula_hawk_wing 1
give @s alexsmobs:tarantula_hawk_wing_fragment 1
give @s alexsmobs:template_caiman_egg 1
give @s alexsmobs:template_crocodile_egg 1
give @s alexsmobs:template_four_caiman_eggs 1
give @s alexsmobs:template_four_crocodile_eggs 1
give @s alexsmobs:template_four_platypus_eggs 1
give @s alexsmobs:template_four_terrapin_eggs 1
give @s alexsmobs:template_platypus_egg 1
give @s alexsmobs:template_terrapin_egg 1
give @s alexsmobs:template_three_caiman_eggs 1
give @s alexsmobs:template_three_crocodile_eggs 1
give @s alexsmobs:template_three_platypus_eggs 1
give @s alexsmobs:template_three_terrapin_eggs 1
give @s alexsmobs:template_two_caiman_eggs 1
give @s alexsmobs:template_two_crocodile_eggs 1
give @s alexsmobs:template_two_platypus_eggs 1
give @s alexsmobs:template_two_terrapin_eggs 1
give @s alexsmobs:tendon_whip 1
give @s alexsmobs:tendon_whip_active 1
give @s alexsmobs:terrapin_bucket 1
give @s alexsmobs:terrapin_egg 1
give @s alexsmobs:transmutation_table 1
give @s alexsmobs:triops_bucket 1
give @s alexsmobs:triops_eggs 1
give @s alexsmobs:unsettling_kimono 1
give @s alexsmobs:vine_lasso 1
give @s alexsmobs:vine_lasso_hand 1
give @s alexsmobs:vine_lasso_inventory 1
give @s alexsmobs:void_worm_beak 1
give @s alexsmobs:void_worm_effigy 1
give @s alexsmobs:void_worm_effigy_inventory 1
give @s alexsmobs:void_worm_eye 1
give @s alexsmobs:void_worm_mandible 1
give @s alexsmobs:wall_inventory 1
give @s alexsmobs:warped_mixture 1
give @s alexsmobs:warped_muscle 1
