# Alex's Mobs - Give All Custom Blocks
give @s alexsmobs:banana_peel 1
give @s alexsmobs:banana_slug_slime_block 1
give @s alexsmobs:banana_slug_slime_block_bubbles 1
give @s alexsmobs:banana_slug_slime_block_inventory 1
give @s alexsmobs:bird_feeder 1
give @s alexsmobs:bird_feeder_empty 1
give @s alexsmobs:bird_feeder_empty_hanging 1
give @s alexsmobs:bird_feeder_filled 1
give @s alexsmobs:bird_feeder_filled_hanging 1
give @s alexsmobs:bird_feeder_hanging 1
give @s alexsmobs:bird_feeder_sugar 1
give @s alexsmobs:bird_feeder_sugar_hanging 1
give @s alexsmobs:bird_feeder_water 1
give @s alexsmobs:bird_feeder_water_hanging 1
give @s alexsmobs:bison_carpet 1
give @s alexsmobs:bison_fur_block 1
give @s alexsmobs:caiman_egg 1
give @s alexsmobs:capsid 1
give @s alexsmobs:crocodile_egg 1
give @s alexsmobs:crystalized_banana_slug_mucus 1
give @s alexsmobs:ender_residue 1
give @s alexsmobs:ender_residue_0 1
give @s alexsmobs:ender_residue_1 1
give @s alexsmobs:ender_residue_2 1
give @s alexsmobs:ender_residue_3 1
give @s alexsmobs:end_pirate_anchor 1
give @s alexsmobs:end_pirate_anchor_winch 1
give @s alexsmobs:end_pirate_door 1
give @s alexsmobs:end_pirate_flag 1
give @s alexsmobs:end_pirate_ship_wheel 1
give @s alexsmobs:end_pirate_trapdoor 1
give @s alexsmobs:end_pirate_trapdoor_bottom 1
give @s alexsmobs:end_pirate_trapdoor_open 1
give @s alexsmobs:end_pirate_trapdoor_top 1
give @s alexsmobs:four_caiman_eggs 1
give @s alexsmobs:four_crocodile_eggs 1
give @s alexsmobs:four_platypus_eggs 1
give @s alexsmobs:four_slightly_cracked_caiman_eggs 1
give @s alexsmobs:four_slightly_cracked_crocodile_eggs 1
give @s alexsmobs:four_slightly_cracked_platypus_eggs 1
give @s alexsmobs:four_slightly_cracked_terrapin_eggs 1
give @s alexsmobs:four_terrapin_eggs 1
give @s alexsmobs:four_very_cracked_caiman_eggs 1
give @s alexsmobs:four_very_cracked_crocodile_eggs 1
give @s alexsmobs:four_very_cracked_platypus_eggs 1
give @s alexsmobs:four_very_cracked_terrapin_eggs 1
give @s alexsmobs:gustmaker 1
give @s alexsmobs:gustmaker_on 1
give @s alexsmobs:gustmaker_vertical 1
give @s alexsmobs:gustmaker_vertical_on 1
give @s alexsmobs:hummingbird_feeder 1
give @s alexsmobs:leafcutter_anthill 1
give @s alexsmobs:leafcutter_ant_chamber 1
give @s alexsmobs:leafcutter_ant_chamber_fungus 1
give @s alexsmobs:orientable_with_top 1
give @s alexsmobs:orientable_with_top_vertical 1
give @s alexsmobs:phantom_sail 1
give @s alexsmobs:phantom_sail_bottom 1
give @s alexsmobs:phantom_sail_middle 1
give @s alexsmobs:phantom_sail_single 1
give @s alexsmobs:phantom_sail_top 1
give @s alexsmobs:platypus_egg 1
give @s alexsmobs:purpur_planks 1
give @s alexsmobs:purpur_planks_inner_stairs 1
give @s alexsmobs:purpur_planks_outer_stairs 1
give @s alexsmobs:purpur_planks_slab 1
give @s alexsmobs:purpur_planks_stairs 1
give @s alexsmobs:purpur_planks_upper_slab 1
give @s alexsmobs:purpur_planks_wall 1
give @s alexsmobs:purpur_planks_wall_inventory 1
give @s alexsmobs:purpur_planks_wall_post 1
give @s alexsmobs:purpur_planks_wall_side 1
give @s alexsmobs:purpur_planks_wall_side_tall 1
give @s alexsmobs:rainbow_glass 1
give @s alexsmobs:rainbow_glass_all 1
give @s alexsmobs:rainbow_glass_down 1
give @s alexsmobs:rainbow_glass_left 1
give @s alexsmobs:rainbow_glass_right 1
give @s alexsmobs:rainbow_glass_up 1
give @s alexsmobs:red_sand_circle 1
give @s alexsmobs:sail 1
give @s alexsmobs:sand_circle 1
give @s alexsmobs:sculk_boomer 1
give @s alexsmobs:sculk_boomer_closed 1
give @s alexsmobs:sculk_boomer_locked 1
give @s alexsmobs:sculk_boomer_open 1
give @s alexsmobs:skunk_spray 1
give @s alexsmobs:slightly_cracked_caiman_egg 1
give @s alexsmobs:slightly_cracked_crocodile_egg 1
give @s alexsmobs:slightly_cracked_platypus_egg 1
give @s alexsmobs:slightly_cracked_terrapin_egg 1
give @s alexsmobs:spectre_sail 1
give @s alexsmobs:spectre_sail_bottom 1
give @s alexsmobs:spectre_sail_middle 1
give @s alexsmobs:spectre_sail_single 1
give @s alexsmobs:spectre_sail_top 1
give @s alexsmobs:straddlite_block 1
give @s alexsmobs:template_caiman_egg 1
give @s alexsmobs:template_crocodile_egg 1
give @s alexsmobs:template_four_caiman_eggs 1
give @s alexsmobs:template_four_crocodile_eggs 1
give @s alexsmobs:template_four_platypus_eggs 1
give @s alexsmobs:template_four_terrapin_eggs 1
give @s alexsmobs:template_platypus_egg 1
give @s alexsmobs:template_terrapin_egg 1
give @s alexsmobs:template_three_caiman_eggs 1
give @s alexsmobs:template_three_crocodile_eggs 1
give @s alexsmobs:template_three_platypus_eggs 1
give @s alexsmobs:template_three_terrapin_eggs 1
give @s alexsmobs:template_two_caiman_eggs 1
give @s alexsmobs:template_two_crocodile_eggs 1
give @s alexsmobs:template_two_platypus_eggs 1
give @s alexsmobs:template_two_terrapin_eggs 1
give @s alexsmobs:terrapin_egg 1
give @s alexsmobs:three_caiman_eggs 1
give @s alexsmobs:three_crocodile_eggs 1
give @s alexsmobs:three_platypus_eggs 1
give @s alexsmobs:three_slightly_cracked_caiman_eggs 1
give @s alexsmobs:three_slightly_cracked_crocodile_eggs 1
give @s alexsmobs:three_slightly_cracked_platypus_eggs 1
give @s alexsmobs:three_slightly_cracked_terrapin_eggs 1
give @s alexsmobs:three_terrapin_eggs 1
give @s alexsmobs:three_very_cracked_caiman_eggs 1
give @s alexsmobs:three_very_cracked_crocodile_eggs 1
give @s alexsmobs:three_very_cracked_platypus_eggs 1
give @s alexsmobs:three_very_cracked_terrapin_eggs 1
give @s alexsmobs:transmutation_table 1
give @s alexsmobs:triops_eggs 1
give @s alexsmobs:two_caiman_eggs 1
give @s alexsmobs:two_crocodile_eggs 1
give @s alexsmobs:two_platypus_eggs 1
give @s alexsmobs:two_slightly_cracked_caiman_eggs 1
give @s alexsmobs:two_slightly_cracked_crocodile_eggs 1
give @s alexsmobs:two_slightly_cracked_platypus_eggs 1
give @s alexsmobs:two_slightly_cracked_terrapin_eggs 1
give @s alexsmobs:two_terrapin_eggs 1
give @s alexsmobs:two_very_cracked_caiman_eggs 1
give @s alexsmobs:two_very_cracked_crocodile_eggs 1
give @s alexsmobs:two_very_cracked_platypus_eggs 1
give @s alexsmobs:two_very_cracked_terrapin_eggs 1
give @s alexsmobs:very_cracked_caiman_egg 1
give @s alexsmobs:very_cracked_crocodile_egg 1
give @s alexsmobs:very_cracked_platypus_egg 1
give @s alexsmobs:very_cracked_terrapin_egg 1
give @s alexsmobs:void_worm_beak 1
give @s alexsmobs:void_worm_effigy 1
give @s alexsmobs:void_worm_effigy_inventory 1
give @s alexsmobs:wall_inventory 1
